"""Add user relationship to Post

Revision ID: 0b8f1c819f85
Revises: 430e816ff3e2
Create Date: 2024-12-08 13:53:20.691112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8f1c819f85'
down_revision = '430e816ff3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        # Add the user_id column
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        
        # Create the foreign key constraint
        batch_op.create_foreign_key(
            'fk_posts_user_id',  # Name of the constraint
            'users',              # Referenced table
            ['user_id'],          # Columns in 'posts' table
            ['id']                # Referenced column in 'users' table
        )
        
        # Drop the 'author' column
        #batch_op.drop_column('author')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_posts_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
