"""Create User model

Revision ID: 430e816ff3e2
Revises: fb16af5043b4
Create Date: 2024-12-08 13:50:04.893659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430e816ff3e2'
down_revision = 'fb16af5043b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
